### ISSUE TITLE
Improve development experience of deployment/testing

### ISSUE THREAD

**Issue by Yantrio** [opentofu/registry-alpha#6]
Right now this requires route53 set up and configured, and in reality we should be able to test this with a raw API gateway for rapid development.

The downside of a raw API gateway is that the stage is included as part of the URL, and this causes issues with clients that expect the url to be at the root of a subdomain

ie. registry.mydomain.co instead of mydomain.co/registry

We should find a way to deploy and develop things with speed so we dont require a full production setup.

Sub tasks
- [x] #45  
- [x] #42  
- [x] #41
- [x] #50
- [x] #51

**Comment by Yantrio** [comment]
Note for future engineers coming to this:

Right now to deploy everything, if the DNS records are not in place before we try and generate the certificate, the validation phase fails.

This means that we have to switch the order of things up or drop this requirement completely for quick dev.

**Comment by eranelbaz** [comment]
Summary of our conversation
> The state is managed in a bucket on that account, no locking yet though. just a raw S3 bucket.
so the next steps to deploy is
Introduce locking
Open up the bucket permissions to allow other federated AWS users to write to the bucket

**Comment by eranelbaz** [comment]
We can maybe also drop `aws_route53_zone` + `domain_name` so that we'll use the auto generated API gw URL, without the need to request for DNS name

**Comment by RLRabinowitz** [comment]
@Yantrio what's the scope of this issue if OpenTF can't use registry URLs that look like `https://<apigatewayaddress>/<stagename>`?

Seems like this is not really possible, and we need a way to make the IaC here not involve any manual actions (or at least, have a README spelling out what needs to be done)
Also, we'd probably need an environment variable that'll control the default registry URL, so that anyone working on the registry could test it out (or, just have anyone testing out the registry explicitly pick his registry's URL)

**Comment by eranelbaz** [comment]
Closing as we now can deploy multiple sandbox stacks
