### ISSUE TITLE
Caching underlying release listing instead of provider version listing.

### ISSUE THREAD

**Issue by cube2222** [opentofu/registry-alpha#97]
I believe we could do a much better job of caching.

When calling a single provider download endpoint we have a FindRelease function and this underneath actually lists all releases. That doesn’t sound extremely efficient but I think it actually opens the door to **much** better caching on the DynamoDB side.

Right now in DynamoDB we cache on the listProviderVersions level. This means we’ll basically make 1 API call * page count per provider requested and per unique version requested in an hour. That could be quite a lot.

**But**, _we could be caching on the github.FetchReleaseNodes level_. This way both the provider listing and single provider version download URL would reuse the same underlying release listing cache. And with this we’re down to 1 API call * page count per provider requested, **period**. No additional calls per version to download. This should also make downloading unique versions much faster (as the cache is already populated). This would create an upper bound on the number of API calls for the provider part of the registry to ~2k (provider count) * average release pages count per hour. In practice I expect most of those provider are unused, so it would be even much much smaller.

This should completely solve github rate limit issues, even with the 5k requests per hour limit. WDYT?

**Comment by RLRabinowitz** [comment]
This does seem like a nice way to reduce the amount of API calls to GitHub, it's a great suggestion.

~~However, we should evaluate our performance and stress-handling as a whole, and make sure that this solution will actually help us handle stress better. Stress issues might originate from other areas first, so it should be our priority to figure out where do we encounter issues under stress, and prioritize~~
I understand now that the motive here is to avoid hitting the 5k requests per hour limit, and not to avoid general stress of the registry. This indeed should help us out here

**Comment by RLRabinowitz** [comment]
We should also adapt this to the `RepositoryExists` API as well, as it's also bound to hit the limit

**Comment by rumenvasilev** [comment]
Is it what you're suggesting is to populate the cache as part of that `fetchFromGithub()` call?
I left a comment in the linked PR for the same problem, but with a slightly different idea - https://github.com/opentofu/registry/pull/99#discussion_r1337825091.
Perhaps it might be more efficient to not overload the ad-hoc fetch functionality (in response to get-provider-versions api call), with additional dynamodb work. + if you only have a single place that updates the DB (e.g. the extra lambda as of now), then you don't need to think about locking and duplicate work/entries. Or are you suggesting to ditch the extra lambda altogether?

**Comment by Yantrio** [comment]
I'll attempt to write down my current feelings here (sorry if this is too verbose)

Right now the application is contending with GitHub API rate-limiting issues, largely due to the redundancy in API calls. Below, I'll talk through the current architecture to pinpoint these shortcomings and proposes a new, more efficient caching strategy.

## Current Architecture and Its Flaws

### Flow

1. User requests `/<namespace>/<name>/versions`.
2. API Lambda checks DynamoDB for the document.
    - If it exists and is stale (older than 55 minutes), returns stale document and triggers `populate_versions` Lambda.
    - If it exists and is fresh, returns the document.
    - If it doesn't exist, fetches data from GitHub synchronously and triggers `populate_versions` Lambda.

This architecture is problematic because it fetches data from GitHub at least twice when populating versions. This redundancy amplifies rate-limiting issues.

#### Mermaid Diagram
```mermaid
sequenceDiagram
    User->>API Lambda: Request /<namespace>/<name>/versions
    API Lambda->>DynamoDB: Check Document
    DynamoDB-->>API Lambda: Return Document Status
    API Lambda->>GitHub: Fetch data if needed
    API Lambda->>populate_versions Lambda: Trigger
    API Lambda-->>User: Return Data
```

#### Mermaid Diagram for `populate_versions` Lambda
```mermaid
sequenceDiagram
    populate_versions Lambda->>DynamoDB: Check Document
    DynamoDB-->>populate_versions Lambda: Return Document Status
    populate_versions Lambda->>GitHub: Fetch data if needed
    populate_versions Lambda->>DynamoDB: Store new data
```

## Proposed Solution

### New GitHub Client

The crux of the new caching strategy lies in the development of a GitHub client.

This new GitHub client should be usable by both lambdas and should be able to:

1. **Reduce API Calls**: Caching responses can drastically cut down the number of outbound requests to GitHub, reducing rate-limiting risks.
2. **Duplicate Request Handling**: A unified caching logic can efficiently serve the same data across multiple Lambdas or services, avoiding redundant API calls.

### Caching Logic

- Checks if a request exists in DynamoDB and is within the TTL of 30 minutes.
- If the data is within TTL, returns the data.
- If the data is stale or doesn't exist, populates it.

### TTL Settings

- TTL for provider version fetching documents in DynamoDB: 55 minutes.
- TTL for GitHub responses in DynamoDB: 30 minutes.

#### Why Lower TTL for GitHub Responses

A TTL of 30 minutes for GitHub responses is set lower than the 55-minute document TTL to maintain a data freshness cushion. This shorter TTL allows room for updates, ensuring that the data isn't overly stale.

#### Mermaid Diagram
```mermaid
sequenceDiagram
    User->>API Lambda: Request /<namespace>/<name>/versions
    API Lambda->>GitHub Client: Check for Data
    GitHub Client->>DynamoDB: Check Document
    DynamoDB-->>GitHub Client: Return Document Status
    GitHub Client->>GitHub: Fetch data if needed
    GitHub Client->>DynamoDB: Store new data
    GitHub Client-->>API Lambda: Return Data
    API Lambda-->>User: Return Data
```

#### Example - RepositoryExists

```go
func (c *Client) RepositoryExists(ctx context.Context, namespace string, name string) (bool, error) {
	key := fmt.Sprintf("RepositoryExists/%s/%s", namespace, name)

	// check dynamodb if this response exists already and is within the allowed ttl
	cachedResponse, err := c.GetItem(ctx, key)
	if err != nil {
		return false, err
	}

	// if we found the document
	if cachedResponse != nil {
		// and it's in an acceptable age range
		if time.Since(cachedResponse.LastUpdated) < AllowedAge {
			slog.Info("Returning cached response", "key", key)
			// cast to a RepositoryExistsResponse
			response, ok := cachedResponse.Response.(RepositoryExistsResponse)
			if !ok {
				return false, fmt.Errorf("failed to cast cached response to RepositoryExistsResponse")
			}
			// return the response
			return response.Exists, nil
		}
	}

	// if not, make the request to GitHub
	exists, err := github.RepositoryExists(ctx, c.managedGhClient, namespace, name)
	if err != nil {
		return false, err
	}

	// Then store that response in dynamodb
	err = c.StoreItem(ctx, key, RepositoryExistsResponse{
		Exists: exists,
	})
	if err != nil {
		return exists, err
	}

	return exists, nil
}
```

## Discussion

### Advantages

- Drastic reduction in direct GitHub API calls by caching responses.
- A unified caching mechanism that's accessible across multiple Lambdas.

### Trade-offs

- Stale data will be served in some situations, but this is considered an acceptable trade-off.
- Additional complexity in the caching logic.

### Open Questions

1. What is the optimal frequency for triggering the `populate_versions` Lambda if we do decide to do this manually?

## Future Considerations

1. Implementing real-time cache invalidation for highly dynamic resources.
2. Optimizing the frequency of the `populate_versions` Lambda based on usage patterns.

**Comment by cube2222** [comment]
Related discussion is happening on the community slack [on this channel](https://opentofucommunity.slack.com/archives/C05UH44L449).

**Comment by serialseb** [comment]
One question I have is, is it part of the design to allow existing terraform installs to pull providers from the opentofu registry registered separately, for those that want to start the migration without giving up yet on the 1.6 features (`terraform test` in my scenario), or is it for alpha 1 only to replace the unnamed default registry (as per the various issues on terraform github issues)?

**Comment by RLRabinowitz** [comment]
A proposal for an alternative approach to caching strategy https://github.com/opentofu/registry/issues/97

Instead of creating a smart caching layer in front of GitHub, we can just use API/GW with caching between the registry code and GitHub. That way, we will immediately have a lot less calls to GitHub API, without the need to manage caching logic ourselves

We could later have smarter caching in our code if needed, but for now I don’t think that’s necessary
Would appreciate to hear your thoughts on this approach

**Comment by RLRabinowitz** [comment]
> One question I have is, is it part of the design to allow existing terraform installs to pull providers from the opentofu registry registered separately, for those that want to start the migration without giving up yet on the 1.6 features (terraform test in my scenario), or is it for alpha 1 only to replace the unnamed default registry (as per the various issues on terraform github issues)?

Yes @serialseb this registry can also act as a custom Terraform registry, if you'd like to do so
However, do note @serialseb that `opentofu`'s Alpha version **does** include the `opentofu test` feature, and we've already put some work into stabilizing it

**Comment by kislerdm** [comment]
I find that the "read-through" strategy proposed by @RLRabinowitz has a great advantage compared the "cache-aside" proposed in the RFC: no need to maintain own logic and additional db table. 

Edit: I reckon I joined the discussion a bit too late 😀 Find the followup on the Arel's proposal in the slack [thread](https://opentofucommunity.slack.com/archives/C05UH44L449/p1695886009650219).

**Comment by Yantrio** [comment]
I'm going to close this now that #103 and #105 are merged. We can discuss more caching strategies and approaches in the future.
